# Generated by Django 5.1.5 on 2025-01-23 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_official', models.CharField(max_length=255)),
                ('name_short', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=50)),
                ('flat', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_street', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('description_problem', models.TextField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.category')),
                ('id_sitizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.citizen')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='id_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.city'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=100)),
                ('flat', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.city')),
                ('id_street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.street')),
            ],
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.service')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('id_appeals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.appeals')),
                ('id_sitizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almet.citizen')),
                ('id_sotrudnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almet.sotrudniki')),
            ],
        ),
        migrations.AddField(
            model_name='appeals',
            name='id_sotrudnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almet.sotrudniki'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almet.citizen')),
                ('id_sotrudnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almet.sotrudniki')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processing_appeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_setting_status', models.DateTimeField()),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('id_appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.appeals')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.status')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='id_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.street'),
        ),
    ]
