# Generated by Django 5.1.5 on 2025-01-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='house',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='id_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almet.city'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='id_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almet.street'),
        ),
    ]
