# Generated by Django 5.1.5 on 2025-01-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0002_alter_citizen_house_alter_citizen_id_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeals',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='appeals/'),
        ),
    ]
