# Generated by Django 5.1.5 on 2025-01-25 08:16

import almet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0003_alter_appeals_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeals',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=almet.models.get_upload_path),
        ),
    ]
