# Generated by Django 5.1.5 on 2025-01-27 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0004_alter_appeals_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeals',
            name='id_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almet.service'),
        ),
    ]
