# Generated by Django 5.1.5 on 2025-01-28 17:11

import almet.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0005_appeals_id_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeals',
            name='photo',
        ),
        migrations.CreateModel(
            name='AppealPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=almet.models.get_upload_path)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='almet.appeals')),
            ],
        ),
    ]
