# Generated by Django 5.1.5 on 2025-02-03 10:29

import almet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0007_appeals_photo_delete_appealphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing_appeals',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=almet.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='tel',
            field=models.TextField(),
        ),
    ]
