# Generated by Django 5.1.5 on 2025-02-03 14:33

import almet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0008_alter_processing_appeals_photo_alter_service_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='flat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='processing_appeals',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=almet.models.get_upload_path_processing),
        ),
    ]
