# Generated by Django 5.1.5 on 2025-02-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0012_remove_message_id_sitizen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='tel',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
