# Generated by Django 5.1.5 on 2025-02-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0014_message_deleted_message_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='edited',
            new_name='is_edited',
        ),
    ]
