# Generated by Django 5.1.5 on 2025-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0015_rename_deleted_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing_appeals',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
