# Generated by Django 5.1.5 on 2025-03-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almet', '0016_processing_appeals_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almet.chatcommand')),
            ],
        ),
    ]
